"""Initial migration.

Revision ID: 14919dffc1ed
Revises: 
Create Date: 2022-10-22 15:10:28.380637

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '14919dffc1ed'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('post')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('post',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('page', sa.VARCHAR(length=100), nullable=True),
    sa.Column('photo', sa.BLOB(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
